version: "3"
services:
  app:
    build:
      context: app
    container_name: app
    depends_on:
      - db
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    networks:
      - nodebridge

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - nodebridge
    depends_on:
      - app
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      - nodebridge
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  nodebridge:
    driver: bridge
